//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoutesPlanning_Demo
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class SpacialDataSet
    {
        public int Id { get; set; }
        public string vehicule { get; set; }
        public Nullable<System.DateTime> dateDepart { get; set; }
        public Nullable<System.DateTime> dateArivee { get; set; }
        public System.Data.Entity.Spatial.DbGeometry trajet { get; set; }
        public Nullable<bool> active { get; set; }

        public static SpacialDataSet GetSpacialDataSet(int id)
        {
            demoDB db = new demoDB();
            return GetSpacialDataSet(id, db);
        }

        public static SpacialDataSet GetSpacialDataSet(int id, demoDB db)
        {
            return db.SpacialDataSets.Single(e => e.Id == id);
        }
    }
}
